@startuml

abstract class Readable {
    read()
}
abstract class Writeable {
    write()
}

class Date {
    int year
    int month
    int day
}

class Customer {
    long id
    float total
    float discount
}

class Product {
    string name
    float price
    bool hasDiscount
}

class Order {
    Customer customer
    Array<Product *> products
    Date date
    float totalWithDiscount
    float total
}

class DailyReport {
    Array<Order *> orders
    Date date
}

Order *- Date
Order o-- Product
Order o-- Customer

DailyReport o-- Order
DailyReport *-- Date

Writeable <|.. Order
Writeable <|. Product
Writeable <|. Customer
Writeable <|. Date
Readable <|. Date
Readable <|. Customer
Readable <|. Product
Readable <|.. Order

@enduml